// This file is generated by omniidl (C++ backend)- omniORB_4_1. Do not edit.
#ifndef __CorbaTube_hh__
#define __CorbaTube_hh__

#ifndef __CORBA_H_EXTERNAL_GUARD__
#include <omniORB4/CORBA.h>
#endif

#ifndef  USE_stub_in_nt_dll
# define USE_stub_in_nt_dll_NOT_DEFINED_CorbaTube
#endif
#ifndef  USE_core_stub_in_nt_dll
# define USE_core_stub_in_nt_dll_NOT_DEFINED_CorbaTube
#endif
#ifndef  USE_dyn_stub_in_nt_dll
# define USE_dyn_stub_in_nt_dll_NOT_DEFINED_CorbaTube
#endif






#ifdef USE_stub_in_nt_dll
# ifndef USE_core_stub_in_nt_dll
#  define USE_core_stub_in_nt_dll
# endif
# ifndef USE_dyn_stub_in_nt_dll
#  define USE_dyn_stub_in_nt_dll
# endif
#endif

#ifdef _core_attr
# error "A local CPP macro _core_attr has already been defined."
#else
# ifdef  USE_core_stub_in_nt_dll
#  define _core_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _core_attr
# endif
#endif

#ifdef _dyn_attr
# error "A local CPP macro _dyn_attr has already been defined."
#else
# ifdef  USE_dyn_stub_in_nt_dll
#  define _dyn_attr _OMNIORB_NTDLL_IMPORT
# else
#  define _dyn_attr
# endif
#endif





_CORBA_MODULE CorbaTube

_CORBA_MODULE_BEG

#ifndef __CorbaTube_mTubeService__
#define __CorbaTube_mTubeService__

  class TubeService;
  class _objref_TubeService;
  class _impl_TubeService;
  
  typedef _objref_TubeService* TubeService_ptr;
  typedef TubeService_ptr TubeServiceRef;

  class TubeService_Helper {
  public:
    typedef TubeService_ptr _ptr_type;

    static _ptr_type _nil();
    static _CORBA_Boolean is_nil(_ptr_type);
    static void release(_ptr_type);
    static void duplicate(_ptr_type);
    static void marshalObjRef(_ptr_type, cdrStream&);
    static _ptr_type unmarshalObjRef(cdrStream&);
  };

  typedef _CORBA_ObjRef_Var<_objref_TubeService, TubeService_Helper> TubeService_var;
  typedef _CORBA_ObjRef_OUT_arg<_objref_TubeService,TubeService_Helper > TubeService_out;

#endif

  // interface TubeService
  class TubeService {
  public:
    // Declarations for this interface type.
    typedef TubeService_ptr _ptr_type;
    typedef TubeService_var _var_type;

    static _ptr_type _duplicate(_ptr_type);
    static _ptr_type _narrow(::CORBA::Object_ptr);
    static _ptr_type _unchecked_narrow(::CORBA::Object_ptr);
    
    static _ptr_type _nil();

    static inline void _marshalObjRef(_ptr_type, cdrStream&);

    static inline _ptr_type _unmarshalObjRef(cdrStream& s) {
      omniObjRef* o = omniObjRef::_unMarshal(_PD_repoId,s);
      if (o)
        return (_ptr_type) o->_ptrToObjRef(_PD_repoId);
      else
        return _nil();
    }

    static _core_attr const char* _PD_repoId;

    // Other IDL defined within this scope.
    
  };

  class _objref_TubeService :
    public virtual ::CORBA::Object,
    public virtual omniObjRef
  {
  public:
    ::CORBA::Boolean has_key(const char* key);
    char* new_key();

    inline _objref_TubeService()  { _PR_setobj(0); }  // nil
    _objref_TubeService(omniIOR*, omniIdentity*);

  protected:
    virtual ~_objref_TubeService();

    
  private:
    virtual void* _ptrToObjRef(const char*);

    _objref_TubeService(const _objref_TubeService&);
    _objref_TubeService& operator = (const _objref_TubeService&);
    // not implemented

    friend class TubeService;
  };

  class _pof_TubeService : public _OMNI_NS(proxyObjectFactory) {
  public:
    inline _pof_TubeService() : _OMNI_NS(proxyObjectFactory)(TubeService::_PD_repoId) {}
    virtual ~_pof_TubeService();

    virtual omniObjRef* newObjRef(omniIOR*,omniIdentity*);
    virtual _CORBA_Boolean is_a(const char*) const;
  };

  class _impl_TubeService :
    public virtual omniServant
  {
  public:
    virtual ~_impl_TubeService();

    virtual ::CORBA::Boolean has_key(const char* key) = 0;
    virtual char* new_key() = 0;
    
  public:  // Really protected, workaround for xlC
    virtual _CORBA_Boolean _dispatch(omniCallHandle&);

  private:
    virtual void* _ptrToInterface(const char*);
    virtual const char* _mostDerivedRepoId();
    
  };


_CORBA_MODULE_END



_CORBA_MODULE POA_CorbaTube
_CORBA_MODULE_BEG

  class TubeService :
    public virtual CorbaTube::_impl_TubeService,
    public virtual ::PortableServer::ServantBase
  {
  public:
    virtual ~TubeService();

    inline ::CorbaTube::TubeService_ptr _this() {
      return (::CorbaTube::TubeService_ptr) _do_this(::CorbaTube::TubeService::_PD_repoId);
    }
  };

_CORBA_MODULE_END



_CORBA_MODULE OBV_CorbaTube
_CORBA_MODULE_BEG

_CORBA_MODULE_END





#undef _core_attr
#undef _dyn_attr



inline void
CorbaTube::TubeService::_marshalObjRef(::CorbaTube::TubeService_ptr obj, cdrStream& s) {
  omniObjRef::_marshal(obj->_PR_getobj(),s);
}




#ifdef   USE_stub_in_nt_dll_NOT_DEFINED_CorbaTube
# undef  USE_stub_in_nt_dll
# undef  USE_stub_in_nt_dll_NOT_DEFINED_CorbaTube
#endif
#ifdef   USE_core_stub_in_nt_dll_NOT_DEFINED_CorbaTube
# undef  USE_core_stub_in_nt_dll
# undef  USE_core_stub_in_nt_dll_NOT_DEFINED_CorbaTube
#endif
#ifdef   USE_dyn_stub_in_nt_dll_NOT_DEFINED_CorbaTube
# undef  USE_dyn_stub_in_nt_dll
# undef  USE_dyn_stub_in_nt_dll_NOT_DEFINED_CorbaTube
#endif

#endif  // __CorbaTube_hh__

